export { default as about } from './about'
export { default as config } from './config'
export { default as home } from './home'
export { default as post } from './post'
export { default as category } from './category'